import type { ApiProfile, AppSettings, ResponsesApiResponse, TaskParams } from '../types'
import { buildApiUrl, readClientDevProxyConfig, shouldUseApiProxy } from './devProxy'
import { getApiErrorMessage, MIME_MAP, normalizeBase64Image, pickActualParams } from './imageApiShared'

export interface AgentApiMessage {
  role: 'user' | 'assistant'
  text: string
  imageDataUrls?: string[]
}

export interface AgentApiResultImage {
  toolCallId?: string
  action?: string
  dataUrl: string
  actualParams?: Partial<TaskParams>
  revisedPrompt?: string
}

export interface AgentApiResult {
  responseId?: string
  text: string
  images: AgentApiResultImage[]
  outputItems: ResponsesApiResponse['output']
  rawResponsePayload?: string
}

const AGENT_IMAGE_INSTRUCTIONS = [
  'You are an image-generation assistant in a multi-turn gallery app.',
  '',
  '## Generating images',
  '- One image_generation call per distinct image. Never merge multiple images into a collage.',
  '- Variations / batches / storyboards / slides → one call each.',
  '- Only generate images when the user explicitly requests them; otherwise reply with text only.',
  '',
  '## Reference image tags',
  'The system automatically inserts `<ref id="..." />` and `<available_refs>` blocks into conversation context to identify images. These tags are generated by the system, not by you — never output them yourself.',
  '- `<ref id="..." />` in user messages point to images the user attached or cited from earlier rounds.',
  '- `<available_refs>` blocks after assistant turns list ids of images generated in that turn.',
  'When the user mentions an image by position or description (e.g. "the first image", "the cat photo"), resolve it to the corresponding id. Use these ids in your image_generation prompts to reference the correct image. Only use ids that already exist in the conversation; never invent ids.',
].join('\n')

function createHeaders(profile: ApiProfile): Record<string, string> {
  return {
    Authorization: `Bearer ${profile.apiKey}`,
    'Content-Type': 'application/json',
  }
}

function createImageTool(params: TaskParams): Record<string, unknown> {
  const tool: Record<string, unknown> = {
    type: 'image_generation',
    action: 'auto',
    size: params.size,
    output_format: params.output_format,
    moderation: params.moderation,
  }

  tool.quality = params.quality

  if (params.output_format !== 'png' && params.output_compression != null) {
    tool.output_compression = params.output_compression
  }

  return tool
}

function createInput(messages: AgentApiMessage[]) {
  return messages.map((message) => {
    const content: Array<Record<string, string>> = [
      { type: message.role === 'user' ? 'input_text' : 'output_text', text: message.text },
    ]

    if (message.role === 'user') {
      for (const dataUrl of message.imageDataUrls ?? []) {
        content.push({ type: 'input_image', image_url: dataUrl })
      }
    }

    return {
      role: message.role,
      content,
    }
  })
}

function extractText(payload: ResponsesApiResponse) {
  const chunks: string[] = []

  for (const item of payload.output ?? []) {
    if (item.type !== 'message') continue
    for (const part of item.content ?? []) {
      if ((part.type === 'output_text' || part.type === 'text') && typeof part.text === 'string') {
        chunks.push(part.text)
      }
    }
  }

  return chunks.join('\n').trim()
}

function extractImages(payload: ResponsesApiResponse, fallbackMime: string): AgentApiResultImage[] {
  const images: AgentApiResultImage[] = []

  for (const item of payload.output ?? []) {
    if (item.type !== 'image_generation_call') continue

    const result = item.result
    if (typeof result === 'string' && result.trim()) {
      images.push({
        toolCallId: typeof item.id === 'string' ? item.id : undefined,
        action: typeof item.action === 'string' ? item.action : undefined,
        dataUrl: normalizeBase64Image(result, fallbackMime),
        actualParams: pickActualParams(item),
        revisedPrompt: typeof item.revised_prompt === 'string' ? item.revised_prompt : undefined,
      })
      continue
    }

    if (result && typeof result === 'object') {
      const b64 = typeof result.b64_json === 'string'
        ? result.b64_json
        : typeof result.image === 'string'
        ? result.image
        : typeof result.data === 'string'
        ? result.data
        : ''
      if (b64.trim()) {
        images.push({
          toolCallId: typeof item.id === 'string' ? item.id : undefined,
          action: typeof item.action === 'string' ? item.action : undefined,
          dataUrl: normalizeBase64Image(b64, fallbackMime),
          actualParams: pickActualParams(item),
          revisedPrompt: typeof item.revised_prompt === 'string' ? item.revised_prompt : undefined,
        })
      }
    }
  }

  return images
}

export async function callAgentResponsesApi(opts: {
  settings: AppSettings
  profile: ApiProfile
  params: TaskParams
  input: unknown
  signal?: AbortSignal
}): Promise<AgentApiResult> {
  const { settings, profile, params, input, signal } = opts
  const mime = MIME_MAP[params.output_format] || 'image/png'
  const proxyConfig = readClientDevProxyConfig()
  const useApiProxy = shouldUseApiProxy(profile.apiProxy, proxyConfig)
  const controller = new AbortController()
  const timeoutId = setTimeout(() => controller.abort(), profile.timeout * 1000)
  const abortFromCaller = () => controller.abort()
  if (signal?.aborted) controller.abort()
  signal?.addEventListener('abort', abortFromCaller, { once: true })

  try {
    const body: Record<string, unknown> = {
      model: profile.model || settings.model,
      instructions: AGENT_IMAGE_INSTRUCTIONS,
      input,
      tools: [createImageTool(params)],
    }

    const response = await fetch(buildApiUrl(profile.baseUrl, 'responses', proxyConfig, useApiProxy), {
      method: 'POST',
      headers: createHeaders(profile),
      cache: 'no-store',
      body: JSON.stringify(body),
      signal: controller.signal,
    })

    if (!response.ok) {
      throw new Error(await getApiErrorMessage(response))
    }

    const payload = await response.json() as ResponsesApiResponse
    return {
      responseId: payload.id,
      text: extractText(payload),
      images: extractImages(payload, mime),
      outputItems: payload.output,
      rawResponsePayload: JSON.stringify(payload, null, 2),
    }
  } finally {
    clearTimeout(timeoutId)
    signal?.removeEventListener('abort', abortFromCaller)
  }
}
